title: Srikar Yaramasu's Website
author: Srikar Yaramasu
email: syaramasu2@ebnet.org
description: > # this means to ignore newlines until "baseurl:"
 Hello my name is Srikar Yaramasu and I am currently in 11th grade. My hobbies incude playing video games and tennis and I also love Fiction novels.
 

# social links
instagram_username: duofinite
github_username:  SrikarYaramasu

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
