title: Srikar Yaramasu's Website
author: Srikar Yaramasu
email: syaramasu2@ebnet.org
description: > # this means to ignore newlines until "baseurl:"
 Hello my name is Srikar Yaramasu and I am currently in 11th grade. My hobbies incude playing video games and tennis and I also love Fiction novels.
 

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
